### ISSUE TITLE
thread 'main' panicked at src\mine.rs:175:6: nonce_worker failed to spawn: Error { kind: NotFound, message: "program not found" }

### ISSUE THREAD

**Issue by Cryptojoyz** [BenjaSOL/ore-cli-gpu#10]
thread 'main' panicked at src\mine.rs:175:6:
nonce_worker failed to spawn: Error { kind: NotFound, message: "program not found" }

I have already replaced my path. But still met this problem.

**Comment by HappyDog2012** [comment]
same problem

**Comment by HappyDog2012** [comment]
> same problem

nonce_worker failed to spawn: Os { code: 2, kind: NotFound, message: "No such file or directory" }

**Comment by feeeei** [comment]
> > same problem
> 
> nonce_worker failed to spawn: Os { code: 2, kind: NotFound, message: "No such file or directory" }

same problem

**Comment by sutiao311** [comment]
The same question, this path to set what path, there is no successful brother to take a screenshot

**Comment by HappyDog2012** [comment]
I might solved the problem? I set the path this way and the "nonce_worker failed to spawn" error disappeared, but next when I started mining, the program stuck.
![path_set](https://github.com/BenjaSOL/ore-cli-gpu/assets/166938979/9908bbfc-0991-4922-a7d9-d3e0a01896b4)
![stuck](https://github.com/BenjaSOL/ore-cli-gpu/assets/166938979/1cdc87e6-3853-4ae4-b15e-69f792eb55e4)
